spring:
  application:
    name: VinaAcademy
  datasource:
    url: jdbc:postgresql://localhost:5432/vinaacademy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 20MB

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG
    root: INFO

application:
  jwt:
    accessToken:
      expiration: 86400
    refreshToken:
      expiration: 2592000

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /